### ISSUE TITLE
开放一个获取变量值的方法

### ISSUE THREAD

**Issue by otakustay** [ecomfe/etpl#50]
因为RIA是专注比较重型解决方案，所以有些东西并不一定与etpl的理念相符，如果此Issue并不符合etpl希望提供的内容，直接Close就好

在系统中，我们会有一些经常会用到的数据，这些数据希望可以在任何的代码中使用，即全局的。其中比较典型的就是枚举，比如我们会在JavaScript中有这样的代码：

```js
var Status = require('foo/enum').Status;
if (entity.status === Status.ENABLED) {
    // ...
}
```

由于JavaScript有AMD的模块管理，自然代码很容易。但是放在模板中，就比较难了，我们希望模板中有这样的代码：

```html
<!-- if: ${entity.status} === ${slot.enum.Status.ENABLED} -->
WTF
<!-- /if -->
```

为了达到这个目标，我们会有一些方案：

1. 在`Model`中加入`Status`这个属性，但这样需要不少额外的编码，在各种`Model`中都要有类似的代码放进许许多多的静态对象
2. 改写`View#getTemplateData`，通过重写`get`方法来解析变量名称，通过一定的规则来获取常量。这种方案看上去美好，但仅限于`View`中使用的模板，在其它地方使用etpl就没有这样的效果，事实是我们确实有很多地方使用着etpl

因此，我希望`etpl`可以有一个方法：

```js
{*} TemplateEngine#getVariableValue({string} variableName})
```

这个方法默认的实现etpl内部肯定是有的，开放到`prototype`上以便系统去定制，通过实现自身的`TemplateEngine`子类来增加各种不同的功能

对于这一功能我希望支持的原因是，我相信etpl内部本身就有这样的逻辑，只是从内部转到`prototype`上来，应该不会影响etpl的体积

**Comment by errorrik** [comment]
这东西内部还真没有，compile后的function独立处理variable的所有事情，和engine就无关了（也不能说无关，filter还是engine在管。

所以，在ETpl上，暂时是无法支持。为啥不在render之前加一层，这层里把一些通用数据merge？

**Comment by otakustay** [comment]
如果无法比较简单的实现，我们还是按`render`时额外做处理来

不希望直接采取`render`方式的原因是有些数据还可能是动态的，整合下来会相对困难，要配合`render`以及`data#get`一起

**Comment by errorrik** [comment]
data getter的功能现在看起来貌似还不够强大，你看看能否支持你的需求，不行的话升级一次。

话说，你确定你们已经升级到3来了？

**Comment by otakustay** [comment]
新北斗会开始使用3，后续几个系统我打算Q2全部完成升级呢……

按这个需求，其实比较好的办法可能是在`render`时，在`data`外再包一层`get`方法出来能实现

**Comment by errorrik** [comment]
突然想起来，新北斗？你今年要折腾多少系统？
