### ISSUE TITLE
变量替换时表达式中有`|`会造成filter表达式解析错误

### ISSUE THREAD

**Issue by LiuJi-Jim** [ecomfe/etpl#55]
e.g.
准备：
```
engine.addFilter('concat', function (source, str) {
    return source + str;
});
```
模板：`Hello ${name|concat("|Liu")}!`
预期输出：`Hello Jim|Liu!`
实际输出：`Hello Jim!`
生成函数片段：`r+=ts(gv("name",["name"]));`——不符合预期

模板改为：`Hello ${name|concat("Liu")}!`
输出：`Hello JimLiu!`——符合预期
生成函数片段：`r+=fs["concat"](ts(gv("name",["name"])),"Liu");`——符合预期

**Comment by errorrik** [comment]
这个是已知问题。

因为ETpl的设计上大多数应用场景是浏览器端，对体积的要求比较高，这里就选择了简单的字符串方式，没有写一个完整的状态机来parse。

所以，对于这种不太常见的场景，我们建议在string里面转义：

```
Hello ${name|concat("\x7cLiu")}!
```
