### ISSUE TITLE
请问 ETPL 是否能应用于 PHP 框架中？

### ISSUE THREAD

**Issue by JasinYip** [ecomfe/etpl#62]
今天留意到 ETPL，看了一下示例，感觉真心棒！正好项目正在选择模板引擎，但后端是使用 Lavavel 框架的，不知道是否有可能将这个模板引擎应用于基于 PHP 的框架当中？

**Comment by errorrik** [comment]
荣幸得到你的认可，不过很抱歉ETpl是一个JS的模板引擎，不能用于PHP环境。

**Comment by JasinYip** [comment]
好吧，看来只能等下次用 Node 的时候用啦~
