### ISSUE TITLE
想要在 hexo 中写个插件用？

### ISSUE THREAD

**Issue by tcdona** [ecomfe/etpl#64]
发现不支持引入其他文件，想加入一个编译缓存【预编译】应该怎么做扩展比较好？
现在是用一个单例暂时解决了。

**Comment by cxy930123** [comment]
我写了一个[插件](https://github.com/cxy930123/hexo-renderer-etpl/)，欢迎参观。

**Comment by yolio2003** [comment]
才看到，差点都忘记这里了，还是很感谢！
