### ISSUE TITLE
etpl能否提供类似classnames包的功能

### ISSUE THREAD

**Issue by zwsf** [ecomfe/etpl#71]
初始对一个元素渲染时根据状态判断是否高亮，目前我这样写:
`
            <li data-interval="5" class="active">5's刷新</li>
            
            <li data-interval="5">5's刷新</li>
            `
能否提供类似classnames包的功能可以这样写:
`<li data-interval="5" class={classNames({active: +${topic_info.interval} === 5})}>5‘s刷新</li>`

**Comment by otakustay** [comment]
etpl是一个基于文本的模板引擎，对DOM/HTML有感知是不符合其定位的，所以这个功能应该不会做

**Comment by errorrik** [comment]
同楼上

**Comment by zwsf** [comment]
嗯

**Comment by zwsf** [comment]
好的
