### ISSUE TITLE
生成HTML时去注释

### ISSUE THREAD

**Issue by otakustay** [ecomfe/etpl#72]
有没有可能给个选项，生成HTML时把注释都去了？

**Comment by tower1229** [comment]
感觉这不是模板引擎的职责

**Comment by otakustay** [comment]
理解楼上的说法，但是考虑到模板引擎在parse阶段其实有这些元数据……

**Comment by errorrik** [comment]
有多迫切？

**Comment by otakustay** [comment]
不是那么迫切，慢慢来

errorrik <notifications@github.com>于2016年6月21日 周二上午11:05写道：

**Comment by errorrik** [comment]
其实我是在问有多想要这个功能，实现的话应该没几行

**Comment by otakustay** [comment]
好吧其实现在来看我不需要了，本来是想通过注释去搞那个依赖管理的，你都直接做完发版本了- -

errorrik <notifications@github.com>于2016年6月22日周三 下午1:35写道：
